name: First workflow
on: workflow_dispatch
jobs: 
  firstjob:
    runs-on: ubuntu-latest
    steps:
      - name: print greeting
        run: echo "hello world!"
      - name: print goodbye
        run: echo "Done-bye!"
